services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: npm start
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev